apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-1
  namespace: myapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80